"""Regenerate the project-owned synthetic video fixture used by video-ingest tests.

The original fixture was described in a now-deleted session report as a six-second,
640x360@6fps instructional video with three original visual cards, an AAC audio tone,
and a WebVTT sidecar -- generated by this project, not sourced externally. It was
lost when runs/ was cleared; this script reproduces it deterministically so the
ingestion tests have a fixture again, without needing any external/licensed content.
"""

from __future__ import annotations

from pathlib import Path

import av
import numpy as np
from PIL import Image, ImageDraw

OUTPUT_DIR = Path(__file__).resolve().parent.parent / "runs" / "2026-08-10_video-ingestion"
WIDTH, HEIGHT = 640, 360
FPS = 6
SECONDS_PER_CARD = 2
CARDS = [
    {"title": "STEP 1", "subtitle": "Inspect the base cage", "color": (90, 140, 235), "label": "BASE"},
    {"title": "STEP 2", "subtitle": "Inspect the evaluated surface", "color": (235, 140, 60), "label": "EVALUATED"},
    {"title": "STEP 3", "subtitle": "Compare front, side, and top", "color": (90, 200, 140), "label": None},
]


def render_card(card: dict) -> Image.Image:
    img = Image.new("RGB", (WIDTH, HEIGHT), (20, 22, 26))
    draw = ImageDraw.Draw(img)
    color = card["color"]
    draw.rounded_rectangle([30, 25, WIDTH - 30, HEIGHT - 25], radius=14, outline=color, width=4)
    draw.text((55, 55), card["title"], fill=color)
    draw.text((55, 90), card["subtitle"], fill=(230, 230, 230))
    if card["title"] == "STEP 1":
        draw.rectangle([80, 130, 190, 200], outline=(230, 230, 230), width=2)
        draw.line([80, 130, 190, 200], fill=(230, 230, 230), width=1)
        draw.text((230, 155), "BASE", fill=(200, 200, 200))
    elif card["title"] == "STEP 2":
        draw.rounded_rectangle([80, 130, 190, 200], radius=20, outline=color, width=3)
        draw.text((230, 155), "EVALUATED", fill=color)
    else:
        for i, label in enumerate(("FRONT", "SIDE", "TOP")):
            cx = 100 + i * 90
            draw.ellipse([cx - 30, 135, cx + 30, 195], outline=color, width=2)
            draw.text((cx - 20, 205), label, fill=(200, 200, 200))
    return img


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    video_path = OUTPUT_DIR / "project_owned_modeling_lesson.mp4"

    container = av.open(str(video_path), mode="w")
    vstream = container.add_stream("h264", rate=FPS)
    vstream.width, vstream.height = WIDTH, HEIGHT
    vstream.pix_fmt = "yuv420p"
    astream = container.add_stream("aac", rate=44100)

    total_frames = FPS * SECONDS_PER_CARD * len(CARDS)
    for frame_index in range(total_frames):
        card = CARDS[frame_index // (FPS * SECONDS_PER_CARD)]
        img = render_card(card)
        frame = av.VideoFrame.from_ndarray(np.array(img), format="rgb24")
        frame = frame.reformat(format="yuv420p")
        for packet in vstream.encode(frame):
            container.mux(packet)

    for packet in vstream.encode():
        container.mux(packet)

    samples_per_chunk = 1024
    # Trim to a whole number of AAC frames so the encoder never pads a trailing
    # partial frame -- that padding previously pushed container duration past
    # 6.000s (to ~6.023s), which shifted the scene-bucketing math by one window.
    raw_total_samples = 44100 * SECONDS_PER_CARD * len(CARDS)
    total_samples = (raw_total_samples // samples_per_chunk) * samples_per_chunk
    t = np.arange(total_samples)
    tone = (0.1 * np.sin(2 * np.pi * 440 * t / 44100)).astype(np.float32)
    for start in range(0, total_samples, samples_per_chunk):
        chunk = tone[start : start + samples_per_chunk]
        if chunk.size == 0:
            continue
        audio_frame = av.AudioFrame.from_ndarray(chunk.reshape(1, -1), format="fltp", layout="mono")
        audio_frame.sample_rate = 44100
        for packet in astream.encode(audio_frame):
            container.mux(packet)
    for packet in astream.encode():
        container.mux(packet)

    container.close()

    vtt_path = OUTPUT_DIR / "project_owned_modeling_lesson.vtt"
    vtt_path.write_text(
        "WEBVTT\n\n"
        "00:00:00.000 --> 00:00:02.000\n"
        "Step 1: inspect the base cage.\n\n"
        "00:00:02.000 --> 00:00:04.000\n"
        "Step 2: inspect the evaluated surface.\n\n"
        "00:00:04.000 --> 00:00:06.000\n"
        "Step 3: compare front, side, and top views.\n",
        encoding="utf-8",
    )
    print("wrote", video_path, "and", vtt_path)


if __name__ == "__main__":
    main()
